# kubectl apply -f 001_log_viewer_daemonset.yaml
# kubectl get pods -n kube-system -l name=usw-log-collector
# kubectl exec -it -n kube-system usw-log-collector-xxxxx /usr/local/bin/bash
# > apk add jq
# > tail -F /var/log/containers/xxxxx.log | jq -r .log

apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: usw-log-collector
  namespace: kube-system
  labels:
    k8s-app: usw-log-collector
spec:
  selector:
    matchLabels:
      name: usw-log-collector
  template:
    metadata:
      labels:
        name: usw-log-collector
    spec:
      tolerations:
      # this toleration is to have the daemonset runnable on master nodes
      # remove it if your masters can't run pods
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      volumes:
      - name: dockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      containers:
      - name: usw-log-collector
        image: bash:5.0
        imagePullPolicy: IfNotPresent
        args: [/bin/sh, -c, 'i=0; while true; do echo "$i: $(date)"; i=$((i+1)); sleep 1; done']
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        volumeMounts:
        - name: dockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
      terminationGracePeriodSeconds: 30
  